version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    container_name: carrot-postgres
    restart: always
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-carrot}
    ports:
      - "5432:5432"

volumes:
  pgdata: {} 